### PR TITLE
Fixes an xray bug and a client crash bug

### PR DESCRIPTION
**Pull request by kmecpp**

### CODE REVIEW

**Comment by MJRLegends** [comment]
Please can you provide details on the bugs your fixing like a screenshot on the xray issue and the crash log. Also which mc version you found these in

**Comment by kmecpp** [comment]
MC 1.7.10

image

```
java.lang.ArrayIndexOutOfBoundsException: 3
	at com.mjr.extraplanets.blocks.planetAndMoonBlocks.Kepler22b.BlockKepler22bMapleTreeLeaves2.func_149691_a(BlockKepler22bMapleTreeLeaves2.java:62)
	at net.minecraft.block.Block.func_149673_e(Block.java:556)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4666)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by MJRLegends** [comment]
Thank you, i will have to double check this isn't a issue in MC1.8+ too

**Comment by kmecpp** [comment]
No problem, do you think you can release an update on curse with the patch when you check that?

**Comment by MJRLegends** [comment]
Yea i plan too

**Comment by MJRLegends** [comment]
@kmecpp sorry for the delay but updates have been released :D

**Pull request merged**
