### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Ezoteric**

### CODE REVIEW

**Comment by MJRLegends** [comment]
Whats this for?

**Comment by MJRLegends** [comment]
Your repo is out of date so this pull request a mess so i cant merge this sorry

**Comment by Ezoteric** [comment]
There are some machines that use the wrong textures for example fuel in has the oil input texture

**Comment by MJRLegends** [comment]
Yea but you have messed up your pull request. Looks like your trying to merge across branches and its all a mess

**Comment by Ezoteric** [comment]
yeah sorry senpai im not good with git :(

**Comment by MJRLegends** [comment]
I have made the changes manually and they already in a released version. So thanks for letting me know about the issue you found

**Pull request closed without merging**
